name: call_reporter

services:
  call_reporter_duckdb:
    image: michaelherman/call_reporter_duckdb
    build:
      context: ./call_reporter_duckdb
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/app/call_reporter_duckdb_home/
  superset:
    image: michaelherman/call_reporter_superset
    build:
      context: ./superset
      dockerfile: Dockerfile
    restart: always
    environment:
      SUPERSET_ADMIN: ${SUPERSET_ADMIN}
      SUPERSET_PASSWORD: ${SUPERSET_PASSWORD}
    ports:
      - "8088:8088"
    volumes:
      - ./shared:/app/superset_home/
      - ./superset/assets:/app/superset_home/assets
    depends_on:
      - call_reporter_duckdb
